// backend/src/services/DepartmentService.ts
// This file manages department-related operations: create, read, update, delete departments.
// It includes business logic for generating department codes if not provided.
import prisma from '../config/prisma';

export const DepartmentService = {
  //function to get all departments
  getAll: async () => {
    return await prisma.department.findMany({ orderBy: { name: 'asc' } });
  },

  //function to create a new department
  create: async (name: string, code?: string) => {
    // this code is generated by converting the name to uppercase,
    // replacing spaces with underscores, and removing diacritics
    const generatedCode = code || name.toUpperCase()
      .replace(/\s+/g, '_')
      .normalize("NFD").replace(/[\u0300-\u036f]/g, "");
      
    return await prisma.department.create({
      data: { name, code: generatedCode }
    });
  },

  //function to update an existing department
  update: async (id: string, name: string) => {
    return await prisma.department.update({ where: { id }, data: { name } });
  },

  //function to delete a department
  delete: async (id: string) => {
    return await prisma.department.delete({ where: { id } });
  }
};